# Configuraciones del servidor
server:
  port: 8090
# Configuraciones de eureka
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: ms-gateway
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/parcial
        registration:
          ms-gateway:
            provider: keycloak
            client-id: client-parcial-back
            client-secret: wYFHe6cwYwJaTH47kAS7iHSa7izsikaF
            scope:
              - openid
            authorization-grant-type: authorization_code
            redirect-uri: 'http://localhost:8090/login/oauth2/code/keycloak'
  # Configuraciones de spring cloud
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: ms-bill
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/**
          filters:
            - StripPrefix=2
